const state = {
  data: null,
  filtered: [],
  filters: { dateFrom: "", dateTo: "", gender: "Alle", age: "Alle", tastingware: "Alle" },
  rawSort: { key: "", direction: "asc" },
};
const colors = ["#0c2830", "#79a879", "#d8b469", "#8fb4c7", "#b36a4c", "#6c7a54", "#bfc7ba"];
const number = new Intl.NumberFormat("de-DE", { maximumFractionDigits: 1 });
const percent = new Intl.NumberFormat("de-DE", { style: "percent", maximumFractionDigits: 1 });
document.addEventListener("DOMContentLoaded", init);
async function init(){ state.data = window.REPORT_DATA || await fetch("data.json").then(r=>r.json()); state.filtered=[...state.data.records]; setupFilters(); setupTabs(); setupRawToggle(); renderAll(); openInitialTab(); }
function setupFilters(){ const {dateRange}=state.data.meta; const from=q("#dateFrom"), to=q("#dateTo"); from.value=dateRange.start||""; to.value=dateRange.end||""; state.filters.dateFrom=from.value; state.filters.dateTo=to.value; fillSelect("#genderFilter", uniqueMulti("genders")); fillSelect("#ageFilter", uniqueMulti("ageGroups")); fillSelect("#tastingwareFilter", uniqueValues("tastingwareAvailable")); from.addEventListener("change",e=>updateFilter("dateFrom",e.target.value)); to.addEventListener("change",e=>updateFilter("dateTo",e.target.value)); q("#genderFilter").addEventListener("change",e=>updateFilter("gender",e.target.value)); q("#ageFilter").addEventListener("change",e=>updateFilter("age",e.target.value)); q("#tastingwareFilter").addEventListener("change",e=>updateFilter("tastingware",e.target.value)); q("#resetFilters").addEventListener("click",()=>{state.filters={dateFrom:dateRange.start||"",dateTo:dateRange.end||"",gender:"Alle",age:"Alle",tastingware:"Alle"}; from.value=state.filters.dateFrom; to.value=state.filters.dateTo; q("#genderFilter").value="Alle"; q("#ageFilter").value="Alle"; q("#tastingwareFilter").value="Alle"; applyFilters();}); }
function fillSelect(sel, values){ q(sel).innerHTML=["Alle",...values].map(v=>`<option value="${escapeAttr(v)}">${escapeHtml(v)}</option>`).join(""); }
function uniqueValues(field){ return [...new Set(state.data.records.map(r=>r[field]).filter(Boolean))].sort(sortHuman); }
function uniqueMulti(field){ return [...new Set(state.data.records.flatMap(r=>r[field]||[]).filter(Boolean))].sort(sortHuman); }
function updateFilter(k,v){ state.filters[k]=v; applyFilters(); }
function applyFilters(){ const f=state.filters; state.filtered=state.data.records.filter(r=>{ const dateOk=(!f.dateFrom||r.date>=f.dateFrom)&&(!f.dateTo||r.date<=f.dateTo); const genderOk=f.gender==="Alle"||(r.genders||[]).includes(f.gender); const ageOk=f.age==="Alle"||(r.ageGroups||[]).includes(f.age); const tastingOk=f.tastingware==="Alle"||r.tastingwareAvailable===f.tastingware; return dateOk&&genderOk&&ageOk&&tastingOk;}); renderAll(); }
function setupTabs(){ qa(".tab").forEach(b=>b.addEventListener("click",()=>activateTab(b.dataset.tab))); }
function activateTab(name){ const b=q(`.tab[data-tab="${name}"]`), p=q(`#tab-${name}`); if(!b||!p)return; qa(".tab").forEach(x=>x.classList.remove("is-active")); qa(".tab-panel").forEach(x=>x.classList.remove("is-active")); b.classList.add("is-active"); p.classList.add("is-active"); }
function openInitialTab(){ const t=location.hash.replace("#",""); if(t){activateTab(t); if(t==="raw") setRawOpen(true);} }
function setupRawToggle(){ q("#rawToggle").addEventListener("click",()=>setRawOpen(q("#rawToggle").getAttribute("aria-expanded")!=="true")); }
function setRawOpen(open){ q("#rawToggle").setAttribute("aria-expanded",String(open)); q("#rawToggle").textContent=open?"Rohdaten ausblenden":"Rohdaten anzeigen"; q("#rawWrap").hidden=!open; }
function calculateStats(rows){ const responses=rows.length,totalSales=sum(rows,"salesUnits"),pure=sum(rows,"pureShots"),mixed=sum(rows,"mixedShots"),shots=pure+mixed; return {responses,totalSales,avgSales:responses?totalSales/responses:0,pure,mixed,shots,avgShots:responses?shots/responses:0,tastingToSaleRate:shots?totalSales/shots:0,tastingwareNo:rows.filter(r=>r.tastingwareAvailable==="Nein").length}; }
function renderAll(){ const rows=state.filtered, stats=calculateStats(rows); renderHero(stats); renderKpis(stats); renderCharts(rows,stats); renderInsights(rows,stats); renderRaw(rows); }
function renderHero(s){ const d=state.data.meta.dateRange; q("#reportPeriod").textContent=d.start&&d.end?`Zeitraum: ${formatDate(d.start)} bis ${formatDate(d.end)}`:"Zeitraum: nicht eindeutig ableitbar"; q("#executiveSummary").textContent=`Aus ${state.data.summary.responses} Promotion-Schichten wurden ${number.format(state.data.summary.totalShots)} Tastings und ${number.format(state.data.summary.totalSalesUnits)} Verkäufe erfasst. In der aktuellen Filteransicht liegen ${number.format(s.responses)} Schichten mit ${number.format(s.shots)} Tastings und ${number.format(s.totalSales)} Verkäufen vor.`; }
function renderKpis(s){ const cards=[["Schichten",number.format(s.responses),"erfasste Promotion-Einsätze"],["Tastings gesamt",number.format(s.shots),`${number.format(s.avgShots)} Tastings / Schicht`],["GIN MARE pur",number.format(s.pure),"ausgegebene pure Shots"],["GIN & Tonic",number.format(s.mixed),"gemischte Tasting Shots"],["Verkäufe",number.format(s.totalSales),`${number.format(s.avgSales)} Stück / Schicht`],["Tasting → Verkauf",percent.format(s.tastingToSaleRate),"Stückverkäufe je Tasting"],["Tastingware Nein",number.format(s.tastingwareNo),"Schichten mit Engpass"],["Ø Verkäufe",number.format(s.avgSales),"Durchschnitt im Filter"]]; q("#kpiGrid").innerHTML=cards.map(([l,v,f])=>`<article class="kpi-card"><p class="kpi-label">${l}</p><p class="kpi-value">${v}</p><p class="kpi-foot">${f}</p></article>`).join(""); }
function renderCharts(rows,s){ renderDonut("#genderChart", countMulti(rows,"genders")); renderBars("#ageChart", countMulti(rows,"ageGroups")); renderDonut("#tastingwareChart", countBy(rows,"tastingwareAvailable")); renderGroupedBars("#activationChart", groupByDateMulti(rows)); renderBars("#shotMixChart", {"Pur":s.pure,"Gin & Tonic":s.mixed}, {keepOrder:true}); renderBars("#obstacleChart", obstacleTotals(rows), {horizontal:true}); }
function renderInsights(rows,s){ const obstacles=Object.entries(obstacleTotals(rows)).sort((a,b)=>b[1]-a[1]); const top=obstacles[0]||["nicht eindeutig",0]; const best=groupByDateMulti(rows).sort((a,b)=>b.sales-a.sales)[0]; const mix=s.shots?s.mixed/s.shots:0; q("#summaryInsights").innerHTML=[["Hohe Sampling-Leistung",`${number.format(s.shots)} Tastings wurden in der aktuellen Ansicht ausgegeben.`],["Absatzhebel",`${number.format(s.totalSales)} Verkäufe entsprechen ${percent.format(s.tastingToSaleRate)} Verkäufen je Tasting.`],["Hauptbarriere",`${top[0]} wurde ${number.format(top[1])}-mal als Kaufhindernis genannt.`]].map(insightItem).join(""); q("#tastingInsights").innerHTML=[["Top-Verkaufstag",best?`${formatDate(best.date)} mit ${number.format(best.sales)} verkauften Stück.`:"Kein eindeutiger Verkaufstag im Filter."],["Tonic-Präferenz",`${percent.format(mix)} der Tastings wurden als Gin & Tonic ausgegeben.`]].map(insightItem).join(""); q("#conversionInsights").innerHTML=[["Tastings",number.format(s.shots)],["Verkäufe",number.format(s.totalSales)],["Quote",percent.format(s.tastingToSaleRate)]].map(([l,v])=>`<div class="metric-item"><span>${l}</span><span>${v}</span></div>`).join(""); renderThemes(rows); renderQuotes(rows); renderRecommendations(); }
function renderThemes(rows){ const text=rows.flatMap(r=>[...(r.tastingFeedback||[]),...(r.productFeedback||[])]).join(" ").toLowerCase(); const themes=[["Tonic / Serve",["tonic","fever","schweppes","mischen"],"Tonic-Empfehlungen und Serve-Präferenzen sind ein starker Gesprächsanker."],["Handgepäck",["handgepäck","rückweg","rücktransport","flasche"],"Flug- und Gepäcklogik beeinflusst Kaufentscheidungen deutlich."],["Verfügbarkeit",["fehl", "nicht", "taschen", "artikel"],"Fehlende Artikel oder POS-Zugaben sollten vor Einsatzbeginn geprüft werden."],["Preis",["preis","teuer"],"Preisargumentation bleibt relevant, wenn Kund:innen vergleichen."]]; q("#feedbackThemes").innerHTML=themes.map(([label,keys,body])=>{ const c=keys.reduce((a,k)=>a+countOccurrences(text,k),0); return `<div class="theme-card"><strong>${label}</strong><span>${c?body:"Im aktuellen Filter kaum eindeutige Hinweise zu diesem Thema."}</span><small>${c} Treffer</small></div>`;}).join(""); }
function renderQuotes(rows){ const items=rows.flatMap(r=>[...(r.tastingFeedback||[]).map(t=>({t,r,type:"Tasting"})),...(r.productFeedback||[]).map(t=>({t,r,type:"Produkt"}))]).filter(x=>x.t).slice(0,10); q("#feedbackQuotes").innerHTML=items.map(x=>`<div class="quote-card">${escapeHtml(polish(x.t))}<small>${formatDate(x.r.date)} · ${x.type} · ID ${escapeHtml(x.r.promoterId)}</small></div>`).join("")||`<div class="quote-card">Keine Freitextantworten im aktuellen Filter.</div>`; }
function renderRecommendations(){ q("#recommendations").innerHTML=[["Tonic-Story schärfen","Fever-Tree Mediterranean und weitere passende Tonic-Optionen aktiv als Serve-Empfehlung nutzen, da Tonic-Präferenzen mehrfach genannt wurden."],["Travel-Size / Handgepäck-Einwand vorbereiten","Promoter:innen mit klaren Antworten für Handgepäck, Weiterflug und Rückkauf-Situationen ausstatten."],["POS-Material vor Einsatz prüfen","Tastingware, Stofftaschen und relevante Artikel vor Schichtbeginn kontrollieren, weil fehlende Zugaben als Kaufargument fehlen können."]].map(([l,t])=>`<div class="recommendation"><strong>${l}</strong>${t}</div>`).join(""); }
function renderRaw(rows){ const meta=state.data.meta; q("#rawMeta").innerHTML=`<span>Quelle: ${escapeHtml(meta.sourceFile.split('/').pop())}</span>`; const cols=meta.columns.filter(c=>c.label); const sorted=sortRawRows(rows); q("#rawTable").innerHTML=`<thead><tr>${cols.map(c=>`<th><button type="button" class="raw-sort" data-key="${escapeAttr(c.key)}">${rawCell(c.label,34,"raw-cell--head")}<span>${sortIndicator(c.key)}</span></button></th>`).join("")}</tr></thead><tbody>${sorted.map(r=>`<tr>${cols.map(c=>`<td>${rawCell(r.raw[c.key]??"",58)}</td>`).join("")}</tr>`).join("")}</tbody>`; qa(".raw-sort").forEach(b=>b.addEventListener("click",()=>updateRawSort(b.dataset.key))); attachTooltips(q("#rawTable")); }
function updateRawSort(key){ if(state.rawSort.key===key) state.rawSort.direction=state.rawSort.direction==="asc"?"desc":"asc"; else state.rawSort={key,direction:"asc"}; renderRaw(state.filtered); }
function sortIndicator(key){ return state.rawSort.key!==key?"↕":state.rawSort.direction==="asc"?"↑":"↓"; }
function sortRawRows(rows){ const {key,direction}=state.rawSort; if(!key)return rows; const factor=direction==="asc"?1:-1; return [...rows].sort((a,b)=>compare(a.raw[key],b.raw[key])*factor); }
function compare(a,b){ const A=norm(a),B=norm(b); if(A.empty&&B.empty)return 0; if(A.empty)return 1; if(B.empty)return -1; if(A.type==="number"&&B.type==="number")return A.value-B.value; return String(A.value).localeCompare(String(B.value),"de",{numeric:true,sensitivity:"base"}); }
function norm(v){ const text=String(v??"").trim(); if(!text)return {empty:true,type:"text",value:""}; const n=Number(text.replace(",",".")); return Number.isFinite(n)&&/^-?\d+([,.]\d+)?$/.test(text)?{empty:false,type:"number",value:n}:{empty:false,type:"text",value:text}; }
function renderDonut(selector, values){ const entries=Object.entries(values).filter(([,v])=>v>0); const total=entries.reduce((a,[,v])=>a+v,0); const c=q(selector); c.classList.add("donut-chart"); if(!entries.length){c.innerHTML=emptyChart();return;} let angle=-90; const slices=entries.map(([label,value],i)=>{ const a=value/total*360, path=donutSlice(88,88,72,38,angle,angle+a); angle+=a; return `<path d="${path}" fill="${colors[i%colors.length]}" data-tip="${escapeAttr(`${label}: ${number.format(value)} (${percent.format(value/total)})`)}"></path>`;}).join(""); const legend=entries.map(([l,v],i)=>`<div class="legend-row"><span style="background:${colors[i%colors.length]}"></span>${escapeHtml(l)} · ${number.format(v)}</div>`).join(""); c.innerHTML=`<svg viewBox="0 0 176 176">${slices}<text x="88" y="92" text-anchor="middle" class="chart-value">${number.format(total)}</text><text x="88" y="112" text-anchor="middle" class="axis-label">Nennungen</text></svg><div class="donut-legend">${legend}</div>`; attachTooltips(c); }
function renderBars(selector, values, options={}){ const entries=(Array.isArray(values)?values:Object.entries(values)).filter(([,v])=>Number(v)>0); if(!options.keepOrder) entries.sort((a,b)=>b[1]-a[1]); const c=q(selector); if(!entries.length){c.innerHTML=emptyChart();return;} const horizontal=options.horizontal, max=Math.max(...entries.map(([,v])=>v)); const width=680, height=Math.max(260, entries.length*(horizontal?52:70)); if(horizontal){ const rows=entries.map(([label,value],i)=>{ const y=28+i*48, bw=max?value/max*380:0; return `<text x="0" y="${y+10}" class="chart-label">${wrapSvgLabel(label,30).map((line,j)=>`<tspan x="0" dy="${j?14:0}">${escapeHtml(line)}</tspan>`).join("")}</text><rect x="220" y="${y}" width="${bw}" height="24" rx="5" fill="${colors[i%colors.length]}" data-tip="${escapeAttr(`${label}: ${number.format(value)}`)}"></rect><text x="${225+bw}" y="${y+17}" class="chart-value">${number.format(value)}</text>`; }).join(""); c.innerHTML=`<svg viewBox="0 0 ${width} ${height}">${rows}</svg>`; } else { const bw=Math.max(42,430/entries.length); const bars=entries.map(([label,value],i)=>{ const h=max?value/max*175:0,x=86+i*(bw+22),y=220-h; return `<rect x="${x}" y="${y}" width="${bw}" height="${h}" rx="6" fill="${colors[i%colors.length]}" data-tip="${escapeAttr(`${label}: ${number.format(value)}`)}"></rect><text x="${x+bw/2}" y="${y-8}" text-anchor="middle" class="chart-value">${number.format(value)}</text><text x="${x+bw/2}" y="248" text-anchor="middle" class="chart-label">${truncate(label,14)}</text>`; }).join(""); c.innerHTML=`<svg viewBox="0 0 ${width} 280"><line x1="54" y1="220" x2="620" y2="220" class="grid-line"></line>${bars}</svg>`; } attachTooltips(c); }
function renderGroupedBars(selector, points){ const c=q(selector); if(!points.length){c.innerHTML=emptyChart();return;} const width=820,height=330,max=Math.max(...points.flatMap(p=>[p.shots,p.sales])); const bw=Math.max(10,560/(points.length*2.6)); const bars=points.map((p,i)=>{ const x=70+i*(bw*2+14), h1=max?p.shots/max*190:0, h2=max?p.sales/max*190:0; return `<rect x="${x}" y="${240-h1}" width="${bw}" height="${h1}" rx="4" fill="${colors[1]}" data-tip="${escapeAttr(`${formatDate(p.date)}: ${number.format(p.shots)} Tastings`)}"></rect><rect x="${x+bw+4}" y="${240-h2}" width="${bw}" height="${h2}" rx="4" fill="${colors[2]}" data-tip="${escapeAttr(`${formatDate(p.date)}: ${number.format(p.sales)} Verkäufe`)}"></rect>${i%2===0?`<text x="${x+bw}" y="268" text-anchor="middle" class="chart-label">${formatDateShort(p.date)}</text>`:""}`;}).join(""); c.innerHTML=`<svg viewBox="0 0 ${width} ${height}"><line x1="54" y1="240" x2="760" y2="240" class="grid-line"></line>${bars}<text x="650" y="42" class="legend-text">Grün: Tastings · Gold: Verkäufe</text></svg>`; attachTooltips(c); }
function countMulti(rows,field){ return rows.reduce((a,r)=>{(r[field]&&r[field].length?r[field]:["Nicht erfasst"]).forEach(v=>a[v]=(a[v]||0)+1); return a;},{}); }
function countBy(rows,field){ return rows.reduce((a,r)=>{const k=r[field]||"Nicht erfasst"; a[k]=(a[k]||0)+1; return a;},{}); }
function groupByDateMulti(rows){ const g={}; rows.forEach(r=>{ if(!r.date)return; if(!g[r.date])g[r.date]={date:r.date,shots:0,sales:0}; g[r.date].shots+=Number(r.totalShots||0); g[r.date].sales+=Number(r.salesUnits||0);}); return Object.values(g).sort((a,b)=>a.date.localeCompare(b.date)); }
function obstacleTotals(rows){ const t={}; rows.forEach(r=>(r.obstacles||[]).forEach(o=>{ if(o.toLowerCase().startsWith("sonstiges"))return; t[o]=(t[o]||0)+1;})); return t; }
function sum(rows,field){ return rows.reduce((a,r)=>a+Number(r[field]||0),0); }
function q(s){return document.querySelector(s)} function qa(s){return [...document.querySelectorAll(s)]}
function insightItem([a,b]){ return `<div class="insight-item"><strong>${escapeHtml(a)}</strong>${escapeHtml(b)}</div>`; }
function emptyChart(){ return `<div class="insight-item">Keine Daten in der aktuellen Filterauswahl.</div>`; }
function formatDate(v){ if(!v)return"Nicht erfasst"; return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${v}T00:00:00`)); }
function formatDateShort(v){ return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit"}).format(new Date(`${v}T00:00:00`)); }
function sortHuman(a,b){ return String(a).localeCompare(String(b),"de",{numeric:true}); }
function truncate(v,l){ const t=String(v); return t.length>l?`${t.slice(0,l-1)}…`:t; }
function rawCell(value,maxLength,cls=""){ const text=String(value??"").trim(), short=text.length>maxLength?`${text.slice(0,maxLength-1)}…`:text, tip=text.length>maxLength?` data-tip="${escapeAttr(text)}"`:""; return `<span class="raw-cell ${cls}"${tip}>${escapeHtml(short)}</span>`; }
function countOccurrences(text,needle){ return (text.match(new RegExp(escapeRegex(needle),"g"))||[]).length; }
function polish(t){ return String(t??"").replace(/\s+/g," ").replace(/vorallem/gi,"vor allem").replace(/fevertree/gi,"Fever-Tree").replace(/mediteranes/gi,"Mediterranean").trim(); }
function wrapSvgLabel(value,maxLength){ const words=String(value).split(/\s+/).filter(Boolean), lines=[]; let cur=""; words.forEach(w=>{ const n=cur?`${cur} ${w}`:w; if(n.length>maxLength&&cur){lines.push(cur);cur=w}else cur=n;}); if(cur)lines.push(cur); return lines.slice(0,2); }
function donutSlice(cx,cy,r,t,start,end){ const large=end-start>180?1:0, os=polar(cx,cy,r,end), oe=polar(cx,cy,r,start), is=polar(cx,cy,r-t,start), ie=polar(cx,cy,r-t,end); return [`M ${os.x} ${os.y}`,`A ${r} ${r} 0 ${large} 0 ${oe.x} ${oe.y}`,`L ${is.x} ${is.y}`,`A ${r-t} ${r-t} 0 ${large} 1 ${ie.x} ${ie.y}`,"Z"].join(" "); }
function polar(cx,cy,r,a){ const rad=(a-90)*Math.PI/180; return {x:cx+r*Math.cos(rad), y:cy+r*Math.sin(rad)}; }
function attachTooltips(container){ const tooltip=q("#tooltip"); container.querySelectorAll("[data-tip]").forEach(el=>{ el.addEventListener("mousemove",e=>{tooltip.textContent=el.dataset.tip; tooltip.style.display="block"; tooltip.style.left=`${e.clientX+14}px`; tooltip.style.top=`${e.clientY+14}px`;}); el.addEventListener("mouseleave",()=>tooltip.style.display="none");}); }
function escapeHtml(v){ return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function escapeAttr(v){ return escapeHtml(v); }
function escapeRegex(v){ return String(v).replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); }
